### ISSUE TITLE
Could you please release a version for 32 bit Windows?

### ISSUE THREAD

**Issue by menway** [memakura/s2microbit-ble#1]
Hi @memakura,
Could you please release a version for 32 bit Windows? When I tried to install "s2microbit-ble_installer_v250.exe" on Windows 10 32 bit, it says 64 bit Windows is required. Thank you!

**Comment by memakura** [comment]
Hi @menway,

I am sorry but I have no 32bit environment to test some libraries used in the application (e.g., noble-uwp). So I cannot support 32 bit Windows OS.

**Comment by menway** [comment]
Thank you for your reply. I'll switch to another computer with 64 bit Windows. :-)
